apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ueDoR47eh4xTQKFty1TEBh1yc2I1k2tUgBJmfUvm4WL871imz8NJZGlCk6vUVr4o9yeOEZMcivOYeO7sVO9IKm6KL9gC7iy9Uyq9Kq/WhvBVyB3vdMHrTvBab7pV1tbpstH40nA905k3zvr7JBT9j/SfHc2qq3nOVmTBVn3GRxLo+n2LcOTyoYBhXiRufKzrZ9+muKfrwZimsrnDy31Nq4p6XunBp58VUcXKoZYSTCkuNChZaMI03S0QyeV9cE3epbmG9t7R8D2yJKZK4OLCA+Zt0EnSskHkxAubFTXIGa4H/zv/l3+aiBg/8/Sn7Dc9fasKZhT7dSEXwt+n4wlZq3PVavW8hv64wiXM7gAZF+Dgt1j7qZP6gaUsGUq6Utbl,iv:4xaMA0K3IB5VZ1POR5J11lZWiAPSgpt0b4lwbw3HnGE=,tag:QwbkpR0nVjkTsvZOhI8VBw==,type:str]
    identity.pub: ENC[AES256_GCM,data:941nvmCn/BUjX5wZ1LXKFTinIay4IXjFGEmQWEXmmvDsIDTskQRFAUWoL++Z1feEo4NZA1uYmiLdzlJj8NoASFPV4Q9JnN/7K4WS5Hn3G+aTVsyq+XmDlScNsnOygKG2v1DgH6P1s89dBW6NHAVHoTsNo63lVZklvQqCn2JAA+mi5x/RJhvbEsJBw5L3oQ7wyXnYU3hhnHvAZIZqIpKXY86vCjUZAP5zl8MJD8mF5mbniK6Io2P6SeKa9CL+wT90C5tf1AOSNJCVGE8lkQ==,iv:QnQ0OgGvASJemXiA30t2jTX9GTuGjY/LrQkPBgjHLGI=,tag:T0rj1uMC6OW+1J8CdQ3FCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Muc/fcF8NJumqPq19m8O09fYK1+KMvFO25ynK2SXVFSqknhlDfWSn2OklJNWmh50VkKo6m3Z2B1072ou95+7M75aa8TZJOp4ZvETPaZJPOUzYBespN6u91OgDWxgTTQ5p6dXP7jz215H3FY5KVC3URsK8kMZhy/r3+RyK9NL9Qa6hASaKhr4ikdNn2DgmtWLtJin1J2qnaoCQlkZgaImdWqGzGCElddGJZne,iv:zGRKt4VuDeWnKbFbVtSj+g7hEKFlLPlCADxP5mXyPJA=,tag:lpxnc7v+8ARbUSk0Ae7sfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s6kmj8jq4jrqee9tzqcvpwhrk5jklspdp70jy28fxu92vlncsssj2xlm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDh2SE5oUkJPV3dwYXZI
            U1hmK1Ixc1Y1QlEzZmNtTGs0VGRNVGtReVZJCjA2eVZJb3ZodzhNMDVSSzVhdlJJ
            SUhFTEtRTVkrTFgxVW1XS3UwZmU3cFUKLS0tIDBNZHBndFc4SWdXSzdLR1BUQzNr
            ZUdaLy84d29RNlV0Y05wd29OWnFld2sKGtaWiwp5rBZQI3YMmD3RydEoIhos0nVm
            RbkSx4K7h722wp2226uGz4IIlUDNljSaOKl1+LT3DlKwIF+0dnLaaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T18:56:55Z"
    mac: ENC[AES256_GCM,data:TW4ep6ImtWXb1/JunVRddI+Pb5mvcEeLnQQ8l8qP6w3wZgq1uUHcJfrHvXFbpR2QP7XhWcRSXamBbMxPvaqHnYdBxeJbVa/88Mbko7mfUDk8cUfKcqRmvnd+i1UimbRdNjs8YiBfGgM4gsRl5Qn8+ui8UX4k38JcXNrR/+90Q9g=,iv:sSmn8G0yXm55e09uCIhn9p5HfmtXFudBux2ntWA8NVI=,tag:Tp21eB5SaVE9r0yWDiavsg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
