---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
    # ingress:
    #   main:
    #     enabled: true
    #     hosts:
    #       - host: "wg.${DOMAIN_0}"
    #         paths:
    #           - overrideService:
    #               name: "main"
    #               port: 51821
    #             path: "/"
    #             pathType: "Prefix"
    #     integrations:
    #       certManager:
    #         certificateIssuer: "domain-0-le-prod"
    #         enabled: true
    #     tls:
    #       - hosts:
    #           - "wg.${DOMAIN_0}"
    service:
      vpn:
        type: LoadBalancer
        loadBalancerIP: ${WG_EASY_IP}
        ports:
          vpn:
            port: 1194
    workload:
      main:
        podSpec:
          securityContext:
            sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"
          containers:
            main:
              probes:
                liveness:
                  type: tcp
                readiness:
                  type: tcp
                startup:
                  type: tcp
              env:
                WG_HOST: "${DDNS_URL}"
                WG_DEFAULT_DNS: "${BLOCKY_IP}"
                WG_PORT: "1194"
                #POST_UP: 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -A POSTROUTING -o %i -j MASQUERADE; iptables -A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -A INPUT -i %i -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -A FORWARD -j ACCEPT'
                #POST_DOWN: 'iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -D POSTROUTING -o %i -j MASQUERADE; iptables -A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -D INPUT -i %i -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -D FORWARD -j ACCEPT'
                # PASSWORD_HASH uses bcrypt. You can create a hash at https://bcrypt.online/
                PASSWORD_HASH: "$2y$10$LEKfuEubLBZi5tGNJSTv0.KfyOwZeYzjM65yZeklo.VM/eE44yrAK"
                WG_ALLOWED_IPS: "0.0.0.0/0"
                LANG: "en"
                UI_TRAFFIC_STATS: "false"
